### ISSUE TITLE
TextXSyntaxError, TextXSemanticError when testing unparsing K-channels

### ISSUE THREAD

**Issue by ccluri** [borismarin/pynmodl#1]
https://github.com/borismarin/pynmodl/blob/bb1bbb788de59fa3ddbe3a68aaee55b4f653578d/pynmodl/tests/compiling/unparser/test_neuron.py#L95

I've been trying to batch run the various channels we have at ICG.

Total number of broken channels :  683 (K-channels)
Total number of  UNPARSE TextXSyntaxError  :  216
Percent of the failed :  31.625183016105417

TextXSyntaxError: Expected 'TITLE' or 'UNITS' or 'NEURON' or 'PARAMETER' or 'ASSIGNED' or 'STATE' or 'INITIAL' or 'BREAKPOINT' or 'DERIVATIVE' or 'FUNCTION' or 'PROCEDURE' or 'UNITSON' or 'UNITSOFF' or EOF at position (1, 189) => 'p, ntau } *INDEPENDEN'

Fails at unp(dedent(cleaned_mod_txt)) 
following channel definitions from https://github.com/icgenealogy/icg-channels-K  

'123815_Kaxon.mod', '125152_ka.mod', '114359_km.mod', '180789_kpkj.mod', '144553_kvz_nature.mod', '64229_kdr_v2.mod', '146026_kfast.mod', '135902_kdrpr.mod', '83344_km.mod', '39949_kir2.mod', '182797_IMminret.mod', '140828_kv.mod', '102288_IMmintau.mod', '182134_kaolmkop.mod', '144526_Kv.mod', '145672_Kv4_csi.mod', '20212_kv.mod', '141273_km.mod', '140462_IKt3.mod', '138321_km.mod', '123927_KM.mod', '3793_kd.mod', '144089_kd.mod', '135898_kv.mod', '147514_kv.mod', '180789_kpkjslow.mod', '54903_kv.mod', '135839_km.mod', '28316_IA.mod', '108459_km.mod', '98005_kv4_ch.mod', '136095_A.mod', '136095_kdr2.mod', '37819_km.mod', '123927_kdr.mod', '35358_kdr.mod', '136095_kmbg.mod', '182134_kdrolmkop.mod', '135787_km.mod', '182134_kdrbwb.mod', '64229_kmRT03.mod', '139421_kaolmkop.mod', '122329_kv4_gp.mod', '87473_ka.mod', '123927_ka.mod', '123927_kslow.mod', '20212_Mykca.mod', '122329_kv2_gp.mod', '149737_kslow.mod', '151126_IA.mod', '87473_fn.mod', '64229_kaRT03_v2.mod', '20212_km.mod', '135903_kdrbwb.mod', '151282_kdrbwb.mod', '155057_kdr.mod', '150538_kv.mod', '22203_kslow.mod', '123815_km.mod', '22203_kfast.mod', '7400_kdr.mod', '114394_Km.mod', '141273_kv.mod', '155735_kpkjslow_cn.mod', '64229_k2RT03.mod', '146030_Kdr_ChannelML.mod', '155735_kpkj.mod', '3342_kd_v2.mod', '143604_km.mod', '155057_iks.mod', '185332_kslow.mod', '124043_km.mod', '52034_kdr.mod', '144490_km_v2.mod', '26997_kdr.mod', '135902_kaolmkop.mod', '139421_kdrpr.mod', '64229_kdrRT03.mod', '48332_kpkj.mod', '64229_kdr.mod', '54903_km.mod', '8210_kd3h5.mod', '105385_kv4_gp.mod', '151126_Kdend.mod', '135903_kaolmkop.mod', '37819_kv.mod', '143604_kv.mod', '28316_Kdend.mod', '122329_kcnq_gp.mod', '83523_kfast.mod', '83344_kv.mod', '2488_km.mod', '124063_Bip_Ka.mod', '53451_km.mod', '87585_ichanWT2005.mod', '151126_Kaxon.mod', '181967_IA.mod', '116862_kmbg.mod', '64229_kmRT03_v2.mod', '139421_kapyrkop.mod', '140828_inwardrect.mod', '22203_km.mod', '116096_km.mod', '147514_km.mod', '123815_Kdend.mod', '28316_IAprox.mod', '185858_kdrbwb.mod', '52034_kdrp.mod', '105385_kv3_gp.mod', '116096_kv.mod', '105385_kv2_gp.mod', '141272_hh2F.mod', '113732_km.mod', '135902_kdrpyrkop.mod', '122329_kv3_gp.mod', '22203_kv.mod', '82849_iks.mod', '83523_kv.mod', '181967_Kdend.mod', '117207_kv.mod', '136715_kv.mod', '37819_kdr.mod', '182134_kdrpr.mod', '64229_kaRT03.mod', '123815_IA.mod', '155735_kpkj_cn.mod', '28316_Ksoma.mod', '123815_Ksoma.mod', '116862_kdr2.mod', '155735_kpkj2_cn.mod', '64195_kv.mod', '64229_kdrp_v2.mod', '144089_km.mod', '115356_kdr.mod', '116053_km.mod', '135902_kapyrkop.mod', '115356_ka.mod', '138321_kv.mod', '116053_kv.mod', '146026_kslow.mod', '141272_hh58CW.mod', '181967_Kaxon.mod', '153196_km.mod', '151126_Ksoma.mod', '3342_kd.mod', '113732_kdr.mod', '181967_km.mod', '64195_km.mod', '125152_kdr.mod', '181967_Ksoma.mod', '64229_kdrp.mod', '108458_Kv.mod', '124063_Bip_Kv.mod', '98005_kv2_ch.mod', '123897_kv.mod', '145672_Kv4_csiosi.mod', '141272_hh2CW.mod', '139421_kdrbwb.mod', '144490_km.mod', '144385_kv.mod', '114359_kv.mod', '37819_kleak.mod', '64229_k2RT03_v2.mod', '115356_km.mod', '136803_km.mod', '110560_potassium.mod', '180789_kpkj2.mod', '144089_kdrD.mod', '135902_kdrolmkop.mod', '150538_km.mod', '139421_kdrpyrkop.mod', '102288_IMminret.mod', '125152_kslow.mod', '135903_kdrolmkop.mod', '114394_kv.mod', '37819_kmbg.mod', '182797_IMmintau.mod', '125152_KM.mod', '117459_kleak.mod', '64229_kdrRT03_v2.mod', '37819_kl.mod', '185332_kfast.mod', '97756_KChannel.mod', '33975_kdr.mod', '168858_kvz_nature.mod', '153196_kv.mod', '143442_kv.mod', '135902_kdrbwb.mod', '53451_kv.mod', '185858_km.mod', '151825_kslow.mod', '135903_kdrpr.mod', '154732_km.mod', '39949_ksi.mod', '182134_kapyrkop.mod', '139421_kdrolmkop.mod', '87585_ichanR859C1.mod', '123897_km.mod', '105385_kcnq_gp.mod', '116862_kleak.mod', '28316_Kaxon.mod', '135903_kapyrkop.mod', '136026_kd.mod', '125857_kdr.mod', '7399_kdr.mod', '140828_km.mod', '146030_KA_ChannelML.mod', '144482_kv.mod', '144385_km.mod', '108459_kv.mod', '82849_kdr.mod', '135787_kv.mod', '124043_kdf.mod', '135903_kdrpyrkop.mod', '22203_kvfast.mod', '182134_kdrpyrkop.mod'

Fails at unp(dedent(cleaned_mod_txt)) 
following channel definitions from https://github.com/icgenealogy/icg-channels-K  

Total number of broken channels :  683 (K-channels)
Total number of  UNPARSE TextXSemanticError  :  2
Percent of the failed :  0.29282576866764276

TextXSemanticError: Unknown object "float" of class "Variable" 

'155157_AType_potassium.mod', '105385_kleak_gp.mod'

**Comment by borismarin** [comment]
Hi Chaitanya
Thanks for providing more test files. I am planning to resume development
next month, and it is great to have a variety of mod files to play with.
In any case, the first batch of parse errors seems to be easy to fix: I
haven't added the INDEPENDENT keyword to the grammar (see
https://github.com/borismarin/pynmodl/blob/master/pynmodl/grammar/nmodl.tx).





2017-10-13 13:09 GMT-03:00 Chaitanya Chintaluri <notifications@github.com>:

**Comment by ccluri** [comment]
Fantastic. Super quick reply and an identified solution too! 
Since you say that this is useful to you...

I have run this over all Na and Ca that we curated as well. 
Now stating only TextXSemanticError for these

Na (https://github.com/icgenealogy/icg-channels-Na)
Total number of broken channels :  343
Total number of  UNPARSE TextXSemanticError  :  2
Percent of the failed :  0.5830903790087464
{'150288_nainter.mod', '64195_na_stochastic.mod'}
 

Ca (https://github.com/icgenealogy/icg-channels-Ca)
Total number of broken channels :  350
Total number of  UNPARSE TextXSemanticError  :  1
Percent of the failed :  0.2857142857142857
{'144502_stoca.mod'}

**Comment by ccluri** [comment]
https://github.com/ccluri/icg-channels/blob/18010f70b0a9e8d9cdbe5e033e69f67abcd088f5/sniff_files.py#L160-L166

Is where and how I test these. Cheers!

**Comment by borismarin** [comment]
@ccluri, after __a lot__ of work incorporating loads of _nmodl_ (sometimes obscure and undocumented) syntax into _pynmodl_, I'm happy to report that I've managed to [parse _all_ K channels](https://github.com/borismarin/pynmodl/blob/igc-tests/pynmodl/tests/parsing/test_icgenealogy.py).
There is still a long way to go in term of making something useful with the parsed files (e.g. I haven't incorporated any of the new syntax into the unparser), but having >1000 parsed files is definitely a good start.
You'll notice that I am skipping a number of them - this is because they _do_ contain semantic errors (at least according to [official _nmodl_ documentation](https://www.neuron.yale.edu/neuron/static/docs/help/neuron/nmodl/nmodl.html)), and thus are expected to fail. Most of these errors are minor (missing variable declarations), and the reference compiler (`nrnivmodl`) seems to disregard them. Notice that I'm not doing much on semantic analysis (but enough to catch all those errors ;) ).
We should definitely have a chat at this stage, as we're now in a position to discuss useful things to be done with the files, now that they can be cast into a regular, validated object model.
